// Code generated from the ELLIO Search API field catalog; do not edit.

import { test } from "node:test";
import { deepEqual, equal } from "node:assert/strict";
import { FIELDS, TYPE_OPERATORS } from "../src/fields.generated";

test("catalog exposes exactly the 47 fields of fields.yml", () => {
  deepEqual(Object.keys(FIELDS).sort(), ["ip", "classification", "seen", "spoofable", "rdns", "active_days", "last_seen", "first_seen", "network.port", "network.non_spoofable_port", "network.spoofable_port", "src.asn.number", "src.asn.name", "src.geo.country.code", "src.geo.country.name", "src.geo.city", "src.geo.continent.code", "src.geo.continent.name", "src.geo.latitude", "src.geo.longitude", "dst.geo.country.code", "dst.geo.country.name", "dst.geo.city", "dst.geo.continent.code", "dst.geo.continent.name", "dst.geo.latitude", "dst.geo.longitude", "http.path", "http.user_agent", "ssh.auth.username", "ssh.auth.password", "ssh.auth.attempt_count", "ssh.auth.first_seen", "ssh.auth.last_seen", "fingerprints.muonfp", "fingerprints.ja4", "fingerprints.ja4t", "fingerprints.ja4h", "fingerprints.ja4ssh", "fingerprints.ja3", "tag", "tag_id", "actor", "cve", "mitre_attack.tactics", "mitre_attack.techniques", "mitre_attack.sub_techniques"].sort());
});

test("type operator sets match the fields.yml types block", () => {
  deepEqual(Object.keys(TYPE_OPERATORS).sort(), ["bool", "country", "date", "fingerprint", "float", "int", "ip", "keyword", "mitre", "port", "text"]);
  deepEqual(TYPE_OPERATORS["bool"], { operators: [":", "!:", "=", "!="], wildcards: false, relativeTime: false });
  deepEqual(TYPE_OPERATORS["country"], { operators: [":", "!:", "=", "!=", "IN", "exists", "not_exists"], wildcards: true, relativeTime: false });
  deepEqual(TYPE_OPERATORS["date"], { operators: [":", "=", ">", ">=", "<", "<=", "range"], wildcards: false, relativeTime: true });
  deepEqual(TYPE_OPERATORS["fingerprint"], { operators: [":", "!:", "~:", "!~:", "=", "!=", "IN", "exists", "not_exists"], wildcards: true, relativeTime: false });
  deepEqual(TYPE_OPERATORS["float"], { operators: [":", "!:", "=", "!=", ">", ">=", "<", "<=", "range"], wildcards: false, relativeTime: false });
  deepEqual(TYPE_OPERATORS["int"], { operators: [":", "!:", "=", "!=", ">", ">=", "<", "<=", "IN", "range"], wildcards: false, relativeTime: false });
  deepEqual(TYPE_OPERATORS["ip"], { operators: [":", "!:", "=", "!=", "IN", "range"], wildcards: false, relativeTime: false });
  deepEqual(TYPE_OPERATORS["keyword"], { operators: [":", "!:", "=", "!=", "IN", "exists", "not_exists"], wildcards: true, relativeTime: false });
  deepEqual(TYPE_OPERATORS["mitre"], { operators: [":", "!:", "=", "!=", "IN", "exists", "not_exists"], wildcards: true, relativeTime: false });
  deepEqual(TYPE_OPERATORS["port"], { operators: [":", "!:", "=", "!=", ">", ">=", "<", "<=", "IN", "range"], wildcards: false, relativeTime: false });
  deepEqual(TYPE_OPERATORS["text"], { operators: [":", "!:", "~:", "!~:", "=", "!=", "IN", "exists", "not_exists"], wildcards: true, relativeTime: false });
});

test("per-field metadata matches fields.yml", () => {
  equal(FIELDS["ip"].type, "ip");
  equal(FIELDS["ip"].category, "core");
  equal(FIELDS["ip"].caseInsensitive, false);
  deepEqual(FIELDS["ip"].aliases, []);
  deepEqual(FIELDS["ip"].enumValues, []);
  equal(FIELDS["classification"].type, "keyword");
  equal(FIELDS["classification"].category, "core");
  equal(FIELDS["classification"].caseInsensitive, false);
  deepEqual(FIELDS["classification"].aliases, []);
  deepEqual(FIELDS["classification"].enumValues, ["malicious", "promiscuous", "benign", "unknown"]);
  equal(FIELDS["seen"].type, "bool");
  equal(FIELDS["seen"].category, "core");
  equal(FIELDS["seen"].caseInsensitive, false);
  deepEqual(FIELDS["seen"].aliases, []);
  deepEqual(FIELDS["seen"].enumValues, ["true", "false"]);
  equal(FIELDS["spoofable"].type, "bool");
  equal(FIELDS["spoofable"].category, "core");
  equal(FIELDS["spoofable"].caseInsensitive, false);
  deepEqual(FIELDS["spoofable"].aliases, []);
  deepEqual(FIELDS["spoofable"].enumValues, ["true", "false"]);
  equal(FIELDS["rdns"].type, "text");
  equal(FIELDS["rdns"].category, "core");
  equal(FIELDS["rdns"].caseInsensitive, true);
  deepEqual(FIELDS["rdns"].aliases, []);
  deepEqual(FIELDS["rdns"].enumValues, []);
  equal(FIELDS["active_days"].type, "int");
  equal(FIELDS["active_days"].category, "core");
  equal(FIELDS["active_days"].caseInsensitive, false);
  deepEqual(FIELDS["active_days"].aliases, []);
  deepEqual(FIELDS["active_days"].enumValues, []);
  equal(FIELDS["last_seen"].type, "date");
  equal(FIELDS["last_seen"].category, "temporal");
  equal(FIELDS["last_seen"].caseInsensitive, false);
  deepEqual(FIELDS["last_seen"].aliases, []);
  deepEqual(FIELDS["last_seen"].enumValues, []);
  equal(FIELDS["first_seen"].type, "date");
  equal(FIELDS["first_seen"].category, "temporal");
  equal(FIELDS["first_seen"].caseInsensitive, false);
  deepEqual(FIELDS["first_seen"].aliases, []);
  deepEqual(FIELDS["first_seen"].enumValues, []);
  equal(FIELDS["network.port"].type, "port");
  equal(FIELDS["network.port"].category, "network");
  equal(FIELDS["network.port"].caseInsensitive, false);
  deepEqual(FIELDS["network.port"].aliases, ["port"]);
  deepEqual(FIELDS["network.port"].enumValues, []);
  equal(FIELDS["network.non_spoofable_port"].type, "port");
  equal(FIELDS["network.non_spoofable_port"].category, "network");
  equal(FIELDS["network.non_spoofable_port"].caseInsensitive, false);
  deepEqual(FIELDS["network.non_spoofable_port"].aliases, []);
  deepEqual(FIELDS["network.non_spoofable_port"].enumValues, []);
  equal(FIELDS["network.spoofable_port"].type, "port");
  equal(FIELDS["network.spoofable_port"].category, "network");
  equal(FIELDS["network.spoofable_port"].caseInsensitive, false);
  deepEqual(FIELDS["network.spoofable_port"].aliases, []);
  deepEqual(FIELDS["network.spoofable_port"].enumValues, []);
  equal(FIELDS["src.asn.number"].type, "int");
  equal(FIELDS["src.asn.number"].category, "network");
  equal(FIELDS["src.asn.number"].caseInsensitive, false);
  deepEqual(FIELDS["src.asn.number"].aliases, ["asn"]);
  deepEqual(FIELDS["src.asn.number"].enumValues, []);
  equal(FIELDS["src.asn.name"].type, "keyword");
  equal(FIELDS["src.asn.name"].category, "network");
  equal(FIELDS["src.asn.name"].caseInsensitive, true);
  deepEqual(FIELDS["src.asn.name"].aliases, []);
  deepEqual(FIELDS["src.asn.name"].enumValues, []);
  equal(FIELDS["src.geo.country.code"].type, "country");
  equal(FIELDS["src.geo.country.code"].category, "geolocation");
  equal(FIELDS["src.geo.country.code"].caseInsensitive, false);
  deepEqual(FIELDS["src.geo.country.code"].aliases, ["country"]);
  deepEqual(FIELDS["src.geo.country.code"].enumValues, []);
  equal(FIELDS["src.geo.country.name"].type, "country");
  equal(FIELDS["src.geo.country.name"].category, "geolocation");
  equal(FIELDS["src.geo.country.name"].caseInsensitive, false);
  deepEqual(FIELDS["src.geo.country.name"].aliases, []);
  deepEqual(FIELDS["src.geo.country.name"].enumValues, []);
  equal(FIELDS["src.geo.city"].type, "keyword");
  equal(FIELDS["src.geo.city"].category, "geolocation");
  equal(FIELDS["src.geo.city"].caseInsensitive, true);
  deepEqual(FIELDS["src.geo.city"].aliases, ["city"]);
  deepEqual(FIELDS["src.geo.city"].enumValues, []);
  equal(FIELDS["src.geo.continent.code"].type, "keyword");
  equal(FIELDS["src.geo.continent.code"].category, "geolocation");
  equal(FIELDS["src.geo.continent.code"].caseInsensitive, false);
  deepEqual(FIELDS["src.geo.continent.code"].aliases, []);
  deepEqual(FIELDS["src.geo.continent.code"].enumValues, []);
  equal(FIELDS["src.geo.continent.name"].type, "keyword");
  equal(FIELDS["src.geo.continent.name"].category, "geolocation");
  equal(FIELDS["src.geo.continent.name"].caseInsensitive, false);
  deepEqual(FIELDS["src.geo.continent.name"].aliases, []);
  deepEqual(FIELDS["src.geo.continent.name"].enumValues, []);
  equal(FIELDS["src.geo.latitude"].type, "float");
  equal(FIELDS["src.geo.latitude"].category, "geolocation");
  equal(FIELDS["src.geo.latitude"].caseInsensitive, false);
  deepEqual(FIELDS["src.geo.latitude"].aliases, []);
  deepEqual(FIELDS["src.geo.latitude"].enumValues, []);
  equal(FIELDS["src.geo.longitude"].type, "float");
  equal(FIELDS["src.geo.longitude"].category, "geolocation");
  equal(FIELDS["src.geo.longitude"].caseInsensitive, false);
  deepEqual(FIELDS["src.geo.longitude"].aliases, []);
  deepEqual(FIELDS["src.geo.longitude"].enumValues, []);
  equal(FIELDS["dst.geo.country.code"].type, "country");
  equal(FIELDS["dst.geo.country.code"].category, "geolocation");
  equal(FIELDS["dst.geo.country.code"].caseInsensitive, false);
  deepEqual(FIELDS["dst.geo.country.code"].aliases, []);
  deepEqual(FIELDS["dst.geo.country.code"].enumValues, []);
  equal(FIELDS["dst.geo.country.name"].type, "country");
  equal(FIELDS["dst.geo.country.name"].category, "geolocation");
  equal(FIELDS["dst.geo.country.name"].caseInsensitive, false);
  deepEqual(FIELDS["dst.geo.country.name"].aliases, []);
  deepEqual(FIELDS["dst.geo.country.name"].enumValues, []);
  equal(FIELDS["dst.geo.city"].type, "keyword");
  equal(FIELDS["dst.geo.city"].category, "geolocation");
  equal(FIELDS["dst.geo.city"].caseInsensitive, true);
  deepEqual(FIELDS["dst.geo.city"].aliases, []);
  deepEqual(FIELDS["dst.geo.city"].enumValues, []);
  equal(FIELDS["dst.geo.continent.code"].type, "keyword");
  equal(FIELDS["dst.geo.continent.code"].category, "geolocation");
  equal(FIELDS["dst.geo.continent.code"].caseInsensitive, false);
  deepEqual(FIELDS["dst.geo.continent.code"].aliases, []);
  deepEqual(FIELDS["dst.geo.continent.code"].enumValues, []);
  equal(FIELDS["dst.geo.continent.name"].type, "keyword");
  equal(FIELDS["dst.geo.continent.name"].category, "geolocation");
  equal(FIELDS["dst.geo.continent.name"].caseInsensitive, false);
  deepEqual(FIELDS["dst.geo.continent.name"].aliases, []);
  deepEqual(FIELDS["dst.geo.continent.name"].enumValues, []);
  equal(FIELDS["dst.geo.latitude"].type, "float");
  equal(FIELDS["dst.geo.latitude"].category, "geolocation");
  equal(FIELDS["dst.geo.latitude"].caseInsensitive, false);
  deepEqual(FIELDS["dst.geo.latitude"].aliases, []);
  deepEqual(FIELDS["dst.geo.latitude"].enumValues, []);
  equal(FIELDS["dst.geo.longitude"].type, "float");
  equal(FIELDS["dst.geo.longitude"].category, "geolocation");
  equal(FIELDS["dst.geo.longitude"].caseInsensitive, false);
  deepEqual(FIELDS["dst.geo.longitude"].aliases, []);
  deepEqual(FIELDS["dst.geo.longitude"].enumValues, []);
  equal(FIELDS["http.path"].type, "text");
  equal(FIELDS["http.path"].category, "http");
  equal(FIELDS["http.path"].caseInsensitive, true);
  deepEqual(FIELDS["http.path"].aliases, ["path"]);
  deepEqual(FIELDS["http.path"].enumValues, []);
  equal(FIELDS["http.user_agent"].type, "text");
  equal(FIELDS["http.user_agent"].category, "http");
  equal(FIELDS["http.user_agent"].caseInsensitive, true);
  deepEqual(FIELDS["http.user_agent"].aliases, ["ua", "user_agent"]);
  deepEqual(FIELDS["http.user_agent"].enumValues, []);
  equal(FIELDS["ssh.auth.username"].type, "text");
  equal(FIELDS["ssh.auth.username"].category, "ssh");
  equal(FIELDS["ssh.auth.username"].caseInsensitive, true);
  deepEqual(FIELDS["ssh.auth.username"].aliases, ["username"]);
  deepEqual(FIELDS["ssh.auth.username"].enumValues, []);
  equal(FIELDS["ssh.auth.password"].type, "text");
  equal(FIELDS["ssh.auth.password"].category, "ssh");
  equal(FIELDS["ssh.auth.password"].caseInsensitive, true);
  deepEqual(FIELDS["ssh.auth.password"].aliases, ["password"]);
  deepEqual(FIELDS["ssh.auth.password"].enumValues, []);
  equal(FIELDS["ssh.auth.attempt_count"].type, "int");
  equal(FIELDS["ssh.auth.attempt_count"].category, "ssh");
  equal(FIELDS["ssh.auth.attempt_count"].caseInsensitive, false);
  deepEqual(FIELDS["ssh.auth.attempt_count"].aliases, []);
  deepEqual(FIELDS["ssh.auth.attempt_count"].enumValues, []);
  equal(FIELDS["ssh.auth.first_seen"].type, "date");
  equal(FIELDS["ssh.auth.first_seen"].category, "ssh");
  equal(FIELDS["ssh.auth.first_seen"].caseInsensitive, false);
  deepEqual(FIELDS["ssh.auth.first_seen"].aliases, []);
  deepEqual(FIELDS["ssh.auth.first_seen"].enumValues, []);
  equal(FIELDS["ssh.auth.last_seen"].type, "date");
  equal(FIELDS["ssh.auth.last_seen"].category, "ssh");
  equal(FIELDS["ssh.auth.last_seen"].caseInsensitive, false);
  deepEqual(FIELDS["ssh.auth.last_seen"].aliases, []);
  deepEqual(FIELDS["ssh.auth.last_seen"].enumValues, []);
  equal(FIELDS["fingerprints.muonfp"].type, "fingerprint");
  equal(FIELDS["fingerprints.muonfp"].category, "fingerprints");
  equal(FIELDS["fingerprints.muonfp"].caseInsensitive, false);
  deepEqual(FIELDS["fingerprints.muonfp"].aliases, ["muonfp"]);
  deepEqual(FIELDS["fingerprints.muonfp"].enumValues, []);
  equal(FIELDS["fingerprints.ja4"].type, "fingerprint");
  equal(FIELDS["fingerprints.ja4"].category, "fingerprints");
  equal(FIELDS["fingerprints.ja4"].caseInsensitive, false);
  deepEqual(FIELDS["fingerprints.ja4"].aliases, ["ja4"]);
  deepEqual(FIELDS["fingerprints.ja4"].enumValues, []);
  equal(FIELDS["fingerprints.ja4t"].type, "fingerprint");
  equal(FIELDS["fingerprints.ja4t"].category, "fingerprints");
  equal(FIELDS["fingerprints.ja4t"].caseInsensitive, false);
  deepEqual(FIELDS["fingerprints.ja4t"].aliases, ["ja4t"]);
  deepEqual(FIELDS["fingerprints.ja4t"].enumValues, []);
  equal(FIELDS["fingerprints.ja4h"].type, "fingerprint");
  equal(FIELDS["fingerprints.ja4h"].category, "fingerprints");
  equal(FIELDS["fingerprints.ja4h"].caseInsensitive, false);
  deepEqual(FIELDS["fingerprints.ja4h"].aliases, ["ja4h"]);
  deepEqual(FIELDS["fingerprints.ja4h"].enumValues, []);
  equal(FIELDS["fingerprints.ja4ssh"].type, "fingerprint");
  equal(FIELDS["fingerprints.ja4ssh"].category, "fingerprints");
  equal(FIELDS["fingerprints.ja4ssh"].caseInsensitive, false);
  deepEqual(FIELDS["fingerprints.ja4ssh"].aliases, ["ja4ssh"]);
  deepEqual(FIELDS["fingerprints.ja4ssh"].enumValues, []);
  equal(FIELDS["fingerprints.ja3"].type, "fingerprint");
  equal(FIELDS["fingerprints.ja3"].category, "fingerprints");
  equal(FIELDS["fingerprints.ja3"].caseInsensitive, false);
  deepEqual(FIELDS["fingerprints.ja3"].aliases, ["ja3"]);
  deepEqual(FIELDS["fingerprints.ja3"].enumValues, []);
  equal(FIELDS["tag"].type, "text");
  equal(FIELDS["tag"].category, "intelligence");
  equal(FIELDS["tag"].caseInsensitive, true);
  deepEqual(FIELDS["tag"].aliases, []);
  deepEqual(FIELDS["tag"].enumValues, []);
  equal(FIELDS["tag_id"].type, "text");
  equal(FIELDS["tag_id"].category, "intelligence");
  equal(FIELDS["tag_id"].caseInsensitive, false);
  deepEqual(FIELDS["tag_id"].aliases, []);
  deepEqual(FIELDS["tag_id"].enumValues, []);
  equal(FIELDS["actor"].type, "text");
  equal(FIELDS["actor"].category, "intelligence");
  equal(FIELDS["actor"].caseInsensitive, true);
  deepEqual(FIELDS["actor"].aliases, []);
  deepEqual(FIELDS["actor"].enumValues, []);
  equal(FIELDS["cve"].type, "text");
  equal(FIELDS["cve"].category, "intelligence");
  equal(FIELDS["cve"].caseInsensitive, true);
  deepEqual(FIELDS["cve"].aliases, []);
  deepEqual(FIELDS["cve"].enumValues, []);
  equal(FIELDS["mitre_attack.tactics"].type, "mitre");
  equal(FIELDS["mitre_attack.tactics"].category, "intelligence");
  equal(FIELDS["mitre_attack.tactics"].caseInsensitive, false);
  deepEqual(FIELDS["mitre_attack.tactics"].aliases, ["tactic"]);
  deepEqual(FIELDS["mitre_attack.tactics"].enumValues, []);
  equal(FIELDS["mitre_attack.techniques"].type, "mitre");
  equal(FIELDS["mitre_attack.techniques"].category, "intelligence");
  equal(FIELDS["mitre_attack.techniques"].caseInsensitive, false);
  deepEqual(FIELDS["mitre_attack.techniques"].aliases, ["technique"]);
  deepEqual(FIELDS["mitre_attack.techniques"].enumValues, []);
  equal(FIELDS["mitre_attack.sub_techniques"].type, "mitre");
  equal(FIELDS["mitre_attack.sub_techniques"].category, "intelligence");
  equal(FIELDS["mitre_attack.sub_techniques"].caseInsensitive, false);
  deepEqual(FIELDS["mitre_attack.sub_techniques"].aliases, ["sub_technique"]);
  deepEqual(FIELDS["mitre_attack.sub_techniques"].enumValues, []);
});
