# Code generated from the ELLIO Search API field catalog; do not edit.
"""ELQ field catalog metadata, generated from the ELLIO Search API field catalog."""

__all__ = ["FIELDS", "FIELD_NAMES", "TYPE_OPERATORS"]

TYPE_OPERATORS = {
    "bool": {
        "operators": (":", "!:", "=", "!="),
        "wildcards": False,
        "relative_time": False,
    },
    "country": {
        "operators": (":", "!:", "=", "!=", "IN", "exists", "not_exists"),
        "wildcards": True,
        "relative_time": False,
    },
    "date": {
        "operators": (":", "=", ">", ">=", "<", "<=", "range"),
        "wildcards": False,
        "relative_time": True,
    },
    "fingerprint": {
        "operators": (":", "!:", "~:", "!~:", "=", "!=", "IN", "exists", "not_exists"),
        "wildcards": True,
        "relative_time": False,
    },
    "float": {
        "operators": (":", "!:", "=", "!=", ">", ">=", "<", "<=", "range"),
        "wildcards": False,
        "relative_time": False,
    },
    "int": {
        "operators": (":", "!:", "=", "!=", ">", ">=", "<", "<=", "IN", "range"),
        "wildcards": False,
        "relative_time": False,
    },
    "ip": {
        "operators": (":", "!:", "=", "!=", "IN", "range"),
        "wildcards": False,
        "relative_time": False,
    },
    "keyword": {
        "operators": (":", "!:", "=", "!=", "IN", "exists", "not_exists"),
        "wildcards": True,
        "relative_time": False,
    },
    "mitre": {
        "operators": (":", "!:", "=", "!=", "IN", "exists", "not_exists"),
        "wildcards": True,
        "relative_time": False,
    },
    "port": {
        "operators": (":", "!:", "=", "!=", ">", ">=", "<", "<=", "IN", "range"),
        "wildcards": False,
        "relative_time": False,
    },
    "text": {
        "operators": (":", "!:", "~:", "!~:", "=", "!=", "IN", "exists", "not_exists"),
        "wildcards": True,
        "relative_time": False,
    },
}

FIELDS = {
    "ip": {
        "name": "ip",
        "type": "ip",
        "category": "core",
        "description": "IPv4 address of the observed source. Accepts single IPs and CIDR blocks.",
        "aliases": (),
        "enum": (),
        "examples": ("ip:\"198.51.100.7\"", "ip:\"203.0.113.0/24\""),
        "case_insensitive": False,
    },
    "classification": {
        "name": "classification",
        "type": "keyword",
        "category": "core",
        "description": "ELLIO verdict for the IP.",
        "aliases": (),
        "enum": ("malicious", "promiscuous", "benign", "unknown"),
        "examples": ("classification:malicious",),
        "case_insensitive": False,
    },
    "seen": {
        "name": "seen",
        "type": "bool",
        "category": "core",
        "description": "Whether the IP was observed by the sensor network in the current window.",
        "aliases": (),
        "enum": ("true", "false"),
        "examples": ("seen:true",),
        "case_insensitive": False,
    },
    "spoofable": {
        "name": "spoofable",
        "type": "bool",
        "category": "core",
        "description": "True when the IP never completed a TCP handshake (traffic may be spoofed).",
        "aliases": (),
        "enum": ("true", "false"),
        "examples": ("spoofable:false",),
        "case_insensitive": False,
    },
    "rdns": {
        "name": "rdns",
        "type": "text",
        "category": "core",
        "description": "Reverse DNS name of the IP.",
        "aliases": (),
        "enum": (),
        "examples": ("rdns:\"*.example.com\"",),
        "case_insensitive": True,
    },
    "active_days": {
        "name": "active_days",
        "type": "int",
        "category": "core",
        "description": "Number of days the IP was active in the 91 day window.",
        "aliases": (),
        "enum": (),
        "examples": ("active_days > 30",),
        "case_insensitive": False,
    },
    "last_seen": {
        "name": "last_seen",
        "type": "date",
        "category": "temporal",
        "description": "Most recent observation. Relative form last_seen:7d means \"within the last 7 days\".",
        "aliases": (),
        "enum": (),
        "examples": ("last_seen:1d", "last_seen >= 2026-07-01"),
        "case_insensitive": False,
    },
    "first_seen": {
        "name": "first_seen",
        "type": "date",
        "category": "temporal",
        "description": "First observation. Relative form first_seen:30d means \"first seen within the last 30 days\".",
        "aliases": (),
        "enum": (),
        "examples": ("first_seen:7d", "first_seen:[2026-06-01 TO 2026-06-30]"),
        "case_insensitive": False,
    },
    "network.port": {
        "name": "network.port",
        "type": "port",
        "category": "network",
        "description": "Destination port the IP touched (any handshake state).",
        "aliases": ("port",),
        "enum": (),
        "examples": ("network.port:23", "port IN (22, 23, 2323)"),
        "case_insensitive": False,
    },
    "network.non_spoofable_port": {
        "name": "network.non_spoofable_port",
        "type": "port",
        "category": "network",
        "description": "Destination port with a completed TCP handshake from this IP.",
        "aliases": (),
        "enum": (),
        "examples": ("network.non_spoofable_port:445",),
        "case_insensitive": False,
    },
    "network.spoofable_port": {
        "name": "network.spoofable_port",
        "type": "port",
        "category": "network",
        "description": "Destination port seen only without a completed handshake.",
        "aliases": (),
        "enum": (),
        "examples": ("network.spoofable_port:53",),
        "case_insensitive": False,
    },
    "src.asn.number": {
        "name": "src.asn.number",
        "type": "int",
        "category": "network",
        "description": "Autonomous system number announcing the IP.",
        "aliases": ("asn",),
        "enum": (),
        "examples": ("src.asn.number:13335", "AS13335"),
        "case_insensitive": False,
    },
    "src.asn.name": {
        "name": "src.asn.name",
        "type": "keyword",
        "category": "network",
        "description": "Name of the announcing autonomous system.",
        "aliases": (),
        "enum": (),
        "examples": ("src.asn.name:\"*cloudflare*\"",),
        "case_insensitive": True,
    },
    "src.geo.country.code": {
        "name": "src.geo.country.code",
        "type": "country",
        "category": "geolocation",
        "description": "ISO 3166-1 alpha-2 country code of the source IP.",
        "aliases": ("country",),
        "enum": (),
        "examples": ("src.geo.country.code:US", "country IN (CN, RU)"),
        "case_insensitive": False,
    },
    "src.geo.country.name": {
        "name": "src.geo.country.name",
        "type": "country",
        "category": "geolocation",
        "description": "Country name of the source IP.",
        "aliases": (),
        "enum": (),
        "examples": ("src.geo.country.name:\"United States\"",),
        "case_insensitive": False,
    },
    "src.geo.city": {
        "name": "src.geo.city",
        "type": "keyword",
        "category": "geolocation",
        "description": "City of the source IP.",
        "aliases": ("city",),
        "enum": (),
        "examples": ("src.geo.city:\"Amsterdam\"",),
        "case_insensitive": True,
    },
    "src.geo.continent.code": {
        "name": "src.geo.continent.code",
        "type": "keyword",
        "category": "geolocation",
        "description": "Continent code of the source IP.",
        "aliases": (),
        "enum": (),
        "examples": ("src.geo.continent.code:EU",),
        "case_insensitive": False,
    },
    "src.geo.continent.name": {
        "name": "src.geo.continent.name",
        "type": "keyword",
        "category": "geolocation",
        "description": "Continent name of the source IP.",
        "aliases": (),
        "enum": (),
        "examples": ("src.geo.continent.name:Europe",),
        "case_insensitive": False,
    },
    "src.geo.latitude": {
        "name": "src.geo.latitude",
        "type": "float",
        "category": "geolocation",
        "description": "Latitude of the source IP geolocation.",
        "aliases": (),
        "enum": (),
        "examples": ("src.geo.latitude > 50",),
        "case_insensitive": False,
    },
    "src.geo.longitude": {
        "name": "src.geo.longitude",
        "type": "float",
        "category": "geolocation",
        "description": "Longitude of the source IP geolocation.",
        "aliases": (),
        "enum": (),
        "examples": ("src.geo.longitude < 0",),
        "case_insensitive": False,
    },
    "dst.geo.country.code": {
        "name": "dst.geo.country.code",
        "type": "country",
        "category": "geolocation",
        "description": "Country code of sensors this IP targeted.",
        "aliases": (),
        "enum": (),
        "examples": ("dst.geo.country.code:DE",),
        "case_insensitive": False,
    },
    "dst.geo.country.name": {
        "name": "dst.geo.country.name",
        "type": "country",
        "category": "geolocation",
        "description": "Country name of sensors this IP targeted.",
        "aliases": (),
        "enum": (),
        "examples": ("dst.geo.country.name:Germany",),
        "case_insensitive": False,
    },
    "dst.geo.city": {
        "name": "dst.geo.city",
        "type": "keyword",
        "category": "geolocation",
        "description": "City of sensors this IP targeted.",
        "aliases": (),
        "enum": (),
        "examples": ("dst.geo.city:\"Prague\"",),
        "case_insensitive": True,
    },
    "dst.geo.continent.code": {
        "name": "dst.geo.continent.code",
        "type": "keyword",
        "category": "geolocation",
        "description": "Continent code of sensors this IP targeted.",
        "aliases": (),
        "enum": (),
        "examples": ("dst.geo.continent.code:EU",),
        "case_insensitive": False,
    },
    "dst.geo.continent.name": {
        "name": "dst.geo.continent.name",
        "type": "keyword",
        "category": "geolocation",
        "description": "Continent name of sensors this IP targeted.",
        "aliases": (),
        "enum": (),
        "examples": ("dst.geo.continent.name:Europe",),
        "case_insensitive": False,
    },
    "dst.geo.latitude": {
        "name": "dst.geo.latitude",
        "type": "float",
        "category": "geolocation",
        "description": "Latitude of sensors this IP targeted.",
        "aliases": (),
        "enum": (),
        "examples": ("dst.geo.latitude > 50",),
        "case_insensitive": False,
    },
    "dst.geo.longitude": {
        "name": "dst.geo.longitude",
        "type": "float",
        "category": "geolocation",
        "description": "Longitude of sensors this IP targeted.",
        "aliases": (),
        "enum": (),
        "examples": ("dst.geo.longitude < 0",),
        "case_insensitive": False,
    },
    "http.path": {
        "name": "http.path",
        "type": "text",
        "category": "http",
        "description": "HTTP request path observed from this IP.",
        "aliases": ("path",),
        "enum": (),
        "examples": ("http.path:\"/wp-login.php\"", "http.path:\"*.env\""),
        "case_insensitive": True,
    },
    "http.user_agent": {
        "name": "http.user_agent",
        "type": "text",
        "category": "http",
        "description": "HTTP User-Agent observed from this IP.",
        "aliases": ("ua", "user_agent"),
        "enum": (),
        "examples": ("http.user_agent:\"*zgrab*\"",),
        "case_insensitive": True,
    },
    "ssh.auth.username": {
        "name": "ssh.auth.username",
        "type": "text",
        "category": "ssh",
        "description": "Username attempted in SSH authentication.",
        "aliases": ("username",),
        "enum": (),
        "examples": ("ssh.auth.username:\"root\"",),
        "case_insensitive": True,
    },
    "ssh.auth.password": {
        "name": "ssh.auth.password",
        "type": "text",
        "category": "ssh",
        "description": "Password attempted in SSH authentication.",
        "aliases": ("password",),
        "enum": (),
        "examples": ("ssh.auth.password:\"admin123\"",),
        "case_insensitive": True,
    },
    "ssh.auth.attempt_count": {
        "name": "ssh.auth.attempt_count",
        "type": "int",
        "category": "ssh",
        "description": "Number of SSH authentication attempts for this credential pair.",
        "aliases": (),
        "enum": (),
        "examples": ("ssh.auth.attempt_count > 100",),
        "case_insensitive": False,
    },
    "ssh.auth.first_seen": {
        "name": "ssh.auth.first_seen",
        "type": "date",
        "category": "ssh",
        "description": "First observation of this SSH credential pair.",
        "aliases": (),
        "enum": (),
        "examples": ("ssh.auth.first_seen:7d",),
        "case_insensitive": False,
    },
    "ssh.auth.last_seen": {
        "name": "ssh.auth.last_seen",
        "type": "date",
        "category": "ssh",
        "description": "Most recent observation of this SSH credential pair.",
        "aliases": (),
        "enum": (),
        "examples": ("ssh.auth.last_seen:1d",),
        "case_insensitive": False,
    },
    "fingerprints.muonfp": {
        "name": "fingerprints.muonfp",
        "type": "fingerprint",
        "category": "fingerprints",
        "description": "MuonFP TCP fingerprint (window_size:tcp_options:mss:window_scale).",
        "aliases": ("muonfp",),
        "enum": (),
        "examples": ("fingerprints.muonfp:\"64240:2-4-8-1-3:1460:7\"", "fingerprints.muonfp:\"*:::\""),
        "case_insensitive": False,
    },
    "fingerprints.ja4": {
        "name": "fingerprints.ja4",
        "type": "fingerprint",
        "category": "fingerprints",
        "description": "JA4 TLS client fingerprint.",
        "aliases": ("ja4",),
        "enum": (),
        "examples": ("fingerprints.ja4:\"t13i190800_9dc949149365_97f8aa674fd9\"",),
        "case_insensitive": False,
    },
    "fingerprints.ja4t": {
        "name": "fingerprints.ja4t",
        "type": "fingerprint",
        "category": "fingerprints",
        "description": "JA4T TCP fingerprint.",
        "aliases": ("ja4t",),
        "enum": (),
        "examples": ("fingerprints.ja4t:\"64240_2-4-8-1-3_1460_7\"",),
        "case_insensitive": False,
    },
    "fingerprints.ja4h": {
        "name": "fingerprints.ja4h",
        "type": "fingerprint",
        "category": "fingerprints",
        "description": "JA4H HTTP client fingerprint.",
        "aliases": ("ja4h",),
        "enum": (),
        "examples": ("fingerprints.ja4h:\"ge11nn15enus_42d7418375b7_000000000000_000000000000\"",),
        "case_insensitive": False,
    },
    "fingerprints.ja4ssh": {
        "name": "fingerprints.ja4ssh",
        "type": "fingerprint",
        "category": "fingerprints",
        "description": "JA4SSH fingerprint.",
        "aliases": ("ja4ssh",),
        "enum": (),
        "examples": ("fingerprints.ja4ssh:\"c36s36_c51s80_c0s0\"",),
        "case_insensitive": False,
    },
    "fingerprints.ja3": {
        "name": "fingerprints.ja3",
        "type": "fingerprint",
        "category": "fingerprints",
        "description": "JA3 TLS client fingerprint (MD5). Prefer JA4 where available.",
        "aliases": ("ja3",),
        "enum": (),
        "examples": ("fingerprints.ja3:\"6734f37431670b3ab4292b8f60f29984\"",),
        "case_insensitive": False,
    },
    "tag": {
        "name": "tag",
        "type": "text",
        "category": "intelligence",
        "description": "Human-readable behavior tag assigned by the detection pipeline.",
        "aliases": (),
        "enum": (),
        "examples": ("tag:\"Telnet Bruteforce\"",),
        "case_insensitive": True,
    },
    "tag_id": {
        "name": "tag_id",
        "type": "text",
        "category": "intelligence",
        "description": "Stable identifier of the behavior tag.",
        "aliases": (),
        "enum": (),
        "examples": ("tag_id:\"telnet_bruteforce\"",),
        "case_insensitive": False,
    },
    "actor": {
        "name": "actor",
        "type": "text",
        "category": "intelligence",
        "description": "Known actor or scanner attribution (for example internet measurement companies).",
        "aliases": (),
        "enum": (),
        "examples": ("actor:\"censys\"",),
        "case_insensitive": True,
    },
    "cve": {
        "name": "cve",
        "type": "text",
        "category": "intelligence",
        "description": "CVE identifiers associated with exploitation behavior from this IP.",
        "aliases": (),
        "enum": (),
        "examples": ("cve:\"CVE-2024-3400\"",),
        "case_insensitive": True,
    },
    "mitre_attack.tactics": {
        "name": "mitre_attack.tactics",
        "type": "mitre",
        "category": "intelligence",
        "description": "MITRE ATT&CK tactic IDs derived from assigned tags.",
        "aliases": ("tactic",),
        "enum": (),
        "examples": ("mitre_attack.tactics:TA0043",),
        "case_insensitive": False,
    },
    "mitre_attack.techniques": {
        "name": "mitre_attack.techniques",
        "type": "mitre",
        "category": "intelligence",
        "description": "MITRE ATT&CK technique IDs derived from assigned tags.",
        "aliases": ("technique",),
        "enum": (),
        "examples": ("mitre_attack.techniques:T1595",),
        "case_insensitive": False,
    },
    "mitre_attack.sub_techniques": {
        "name": "mitre_attack.sub_techniques",
        "type": "mitre",
        "category": "intelligence",
        "description": "MITRE ATT&CK sub-technique IDs derived from assigned tags.",
        "aliases": ("sub_technique",),
        "enum": (),
        "examples": ("mitre_attack.sub_techniques:T1595.002",),
        "case_insensitive": False,
    },
}

FIELD_NAMES = tuple(FIELDS)
