# Code generated from the ELLIO Search API field catalog; do not edit.
import unittest

from ellio_elq.fields_generated import FIELDS, TYPE_OPERATORS


class TestGeneratedMetadata(unittest.TestCase):
    def test_catalog_exposes_exactly_the_47_fields_of_fields_yml(self):
        self.assertEqual(sorted(FIELDS), sorted(["ip", "classification", "seen", "spoofable", "rdns", "active_days", "last_seen", "first_seen", "network.port", "network.non_spoofable_port", "network.spoofable_port", "src.asn.number", "src.asn.name", "src.geo.country.code", "src.geo.country.name", "src.geo.city", "src.geo.continent.code", "src.geo.continent.name", "src.geo.latitude", "src.geo.longitude", "dst.geo.country.code", "dst.geo.country.name", "dst.geo.city", "dst.geo.continent.code", "dst.geo.continent.name", "dst.geo.latitude", "dst.geo.longitude", "http.path", "http.user_agent", "ssh.auth.username", "ssh.auth.password", "ssh.auth.attempt_count", "ssh.auth.first_seen", "ssh.auth.last_seen", "fingerprints.muonfp", "fingerprints.ja4", "fingerprints.ja4t", "fingerprints.ja4h", "fingerprints.ja4ssh", "fingerprints.ja3", "tag", "tag_id", "actor", "cve", "mitre_attack.tactics", "mitre_attack.techniques", "mitre_attack.sub_techniques"]))

    def test_type_operator_sets_match_the_fields_yml_types_block(self):
        self.assertEqual(sorted(TYPE_OPERATORS), ["bool", "country", "date", "fingerprint", "float", "int", "ip", "keyword", "mitre", "port", "text"])
        self.assertEqual(
            TYPE_OPERATORS["bool"],
            {"operators": (":", "!:", "=", "!="), "wildcards": False, "relative_time": False},
        )
        self.assertEqual(
            TYPE_OPERATORS["country"],
            {"operators": (":", "!:", "=", "!=", "IN", "exists", "not_exists"), "wildcards": True, "relative_time": False},
        )
        self.assertEqual(
            TYPE_OPERATORS["date"],
            {"operators": (":", "=", ">", ">=", "<", "<=", "range"), "wildcards": False, "relative_time": True},
        )
        self.assertEqual(
            TYPE_OPERATORS["fingerprint"],
            {"operators": (":", "!:", "~:", "!~:", "=", "!=", "IN", "exists", "not_exists"), "wildcards": True, "relative_time": False},
        )
        self.assertEqual(
            TYPE_OPERATORS["float"],
            {"operators": (":", "!:", "=", "!=", ">", ">=", "<", "<=", "range"), "wildcards": False, "relative_time": False},
        )
        self.assertEqual(
            TYPE_OPERATORS["int"],
            {"operators": (":", "!:", "=", "!=", ">", ">=", "<", "<=", "IN", "range"), "wildcards": False, "relative_time": False},
        )
        self.assertEqual(
            TYPE_OPERATORS["ip"],
            {"operators": (":", "!:", "=", "!=", "IN", "range"), "wildcards": False, "relative_time": False},
        )
        self.assertEqual(
            TYPE_OPERATORS["keyword"],
            {"operators": (":", "!:", "=", "!=", "IN", "exists", "not_exists"), "wildcards": True, "relative_time": False},
        )
        self.assertEqual(
            TYPE_OPERATORS["mitre"],
            {"operators": (":", "!:", "=", "!=", "IN", "exists", "not_exists"), "wildcards": True, "relative_time": False},
        )
        self.assertEqual(
            TYPE_OPERATORS["port"],
            {"operators": (":", "!:", "=", "!=", ">", ">=", "<", "<=", "IN", "range"), "wildcards": False, "relative_time": False},
        )
        self.assertEqual(
            TYPE_OPERATORS["text"],
            {"operators": (":", "!:", "~:", "!~:", "=", "!=", "IN", "exists", "not_exists"), "wildcards": True, "relative_time": False},
        )

    def test_per_field_metadata_matches_fields_yml(self):
        self.assertEqual(FIELDS["ip"]["type"], "ip")
        self.assertEqual(FIELDS["ip"]["category"], "core")
        self.assertEqual(FIELDS["ip"]["case_insensitive"], False)
        self.assertEqual(FIELDS["ip"]["aliases"], ())
        self.assertEqual(FIELDS["ip"]["enum"], ())
        self.assertEqual(FIELDS["classification"]["type"], "keyword")
        self.assertEqual(FIELDS["classification"]["category"], "core")
        self.assertEqual(FIELDS["classification"]["case_insensitive"], False)
        self.assertEqual(FIELDS["classification"]["aliases"], ())
        self.assertEqual(FIELDS["classification"]["enum"], ("malicious", "promiscuous", "benign", "unknown"))
        self.assertEqual(FIELDS["seen"]["type"], "bool")
        self.assertEqual(FIELDS["seen"]["category"], "core")
        self.assertEqual(FIELDS["seen"]["case_insensitive"], False)
        self.assertEqual(FIELDS["seen"]["aliases"], ())
        self.assertEqual(FIELDS["seen"]["enum"], ("true", "false"))
        self.assertEqual(FIELDS["spoofable"]["type"], "bool")
        self.assertEqual(FIELDS["spoofable"]["category"], "core")
        self.assertEqual(FIELDS["spoofable"]["case_insensitive"], False)
        self.assertEqual(FIELDS["spoofable"]["aliases"], ())
        self.assertEqual(FIELDS["spoofable"]["enum"], ("true", "false"))
        self.assertEqual(FIELDS["rdns"]["type"], "text")
        self.assertEqual(FIELDS["rdns"]["category"], "core")
        self.assertEqual(FIELDS["rdns"]["case_insensitive"], True)
        self.assertEqual(FIELDS["rdns"]["aliases"], ())
        self.assertEqual(FIELDS["rdns"]["enum"], ())
        self.assertEqual(FIELDS["active_days"]["type"], "int")
        self.assertEqual(FIELDS["active_days"]["category"], "core")
        self.assertEqual(FIELDS["active_days"]["case_insensitive"], False)
        self.assertEqual(FIELDS["active_days"]["aliases"], ())
        self.assertEqual(FIELDS["active_days"]["enum"], ())
        self.assertEqual(FIELDS["last_seen"]["type"], "date")
        self.assertEqual(FIELDS["last_seen"]["category"], "temporal")
        self.assertEqual(FIELDS["last_seen"]["case_insensitive"], False)
        self.assertEqual(FIELDS["last_seen"]["aliases"], ())
        self.assertEqual(FIELDS["last_seen"]["enum"], ())
        self.assertEqual(FIELDS["first_seen"]["type"], "date")
        self.assertEqual(FIELDS["first_seen"]["category"], "temporal")
        self.assertEqual(FIELDS["first_seen"]["case_insensitive"], False)
        self.assertEqual(FIELDS["first_seen"]["aliases"], ())
        self.assertEqual(FIELDS["first_seen"]["enum"], ())
        self.assertEqual(FIELDS["network.port"]["type"], "port")
        self.assertEqual(FIELDS["network.port"]["category"], "network")
        self.assertEqual(FIELDS["network.port"]["case_insensitive"], False)
        self.assertEqual(FIELDS["network.port"]["aliases"], ("port",))
        self.assertEqual(FIELDS["network.port"]["enum"], ())
        self.assertEqual(FIELDS["network.non_spoofable_port"]["type"], "port")
        self.assertEqual(FIELDS["network.non_spoofable_port"]["category"], "network")
        self.assertEqual(FIELDS["network.non_spoofable_port"]["case_insensitive"], False)
        self.assertEqual(FIELDS["network.non_spoofable_port"]["aliases"], ())
        self.assertEqual(FIELDS["network.non_spoofable_port"]["enum"], ())
        self.assertEqual(FIELDS["network.spoofable_port"]["type"], "port")
        self.assertEqual(FIELDS["network.spoofable_port"]["category"], "network")
        self.assertEqual(FIELDS["network.spoofable_port"]["case_insensitive"], False)
        self.assertEqual(FIELDS["network.spoofable_port"]["aliases"], ())
        self.assertEqual(FIELDS["network.spoofable_port"]["enum"], ())
        self.assertEqual(FIELDS["src.asn.number"]["type"], "int")
        self.assertEqual(FIELDS["src.asn.number"]["category"], "network")
        self.assertEqual(FIELDS["src.asn.number"]["case_insensitive"], False)
        self.assertEqual(FIELDS["src.asn.number"]["aliases"], ("asn",))
        self.assertEqual(FIELDS["src.asn.number"]["enum"], ())
        self.assertEqual(FIELDS["src.asn.name"]["type"], "keyword")
        self.assertEqual(FIELDS["src.asn.name"]["category"], "network")
        self.assertEqual(FIELDS["src.asn.name"]["case_insensitive"], True)
        self.assertEqual(FIELDS["src.asn.name"]["aliases"], ())
        self.assertEqual(FIELDS["src.asn.name"]["enum"], ())
        self.assertEqual(FIELDS["src.geo.country.code"]["type"], "country")
        self.assertEqual(FIELDS["src.geo.country.code"]["category"], "geolocation")
        self.assertEqual(FIELDS["src.geo.country.code"]["case_insensitive"], False)
        self.assertEqual(FIELDS["src.geo.country.code"]["aliases"], ("country",))
        self.assertEqual(FIELDS["src.geo.country.code"]["enum"], ())
        self.assertEqual(FIELDS["src.geo.country.name"]["type"], "country")
        self.assertEqual(FIELDS["src.geo.country.name"]["category"], "geolocation")
        self.assertEqual(FIELDS["src.geo.country.name"]["case_insensitive"], False)
        self.assertEqual(FIELDS["src.geo.country.name"]["aliases"], ())
        self.assertEqual(FIELDS["src.geo.country.name"]["enum"], ())
        self.assertEqual(FIELDS["src.geo.city"]["type"], "keyword")
        self.assertEqual(FIELDS["src.geo.city"]["category"], "geolocation")
        self.assertEqual(FIELDS["src.geo.city"]["case_insensitive"], True)
        self.assertEqual(FIELDS["src.geo.city"]["aliases"], ("city",))
        self.assertEqual(FIELDS["src.geo.city"]["enum"], ())
        self.assertEqual(FIELDS["src.geo.continent.code"]["type"], "keyword")
        self.assertEqual(FIELDS["src.geo.continent.code"]["category"], "geolocation")
        self.assertEqual(FIELDS["src.geo.continent.code"]["case_insensitive"], False)
        self.assertEqual(FIELDS["src.geo.continent.code"]["aliases"], ())
        self.assertEqual(FIELDS["src.geo.continent.code"]["enum"], ())
        self.assertEqual(FIELDS["src.geo.continent.name"]["type"], "keyword")
        self.assertEqual(FIELDS["src.geo.continent.name"]["category"], "geolocation")
        self.assertEqual(FIELDS["src.geo.continent.name"]["case_insensitive"], False)
        self.assertEqual(FIELDS["src.geo.continent.name"]["aliases"], ())
        self.assertEqual(FIELDS["src.geo.continent.name"]["enum"], ())
        self.assertEqual(FIELDS["src.geo.latitude"]["type"], "float")
        self.assertEqual(FIELDS["src.geo.latitude"]["category"], "geolocation")
        self.assertEqual(FIELDS["src.geo.latitude"]["case_insensitive"], False)
        self.assertEqual(FIELDS["src.geo.latitude"]["aliases"], ())
        self.assertEqual(FIELDS["src.geo.latitude"]["enum"], ())
        self.assertEqual(FIELDS["src.geo.longitude"]["type"], "float")
        self.assertEqual(FIELDS["src.geo.longitude"]["category"], "geolocation")
        self.assertEqual(FIELDS["src.geo.longitude"]["case_insensitive"], False)
        self.assertEqual(FIELDS["src.geo.longitude"]["aliases"], ())
        self.assertEqual(FIELDS["src.geo.longitude"]["enum"], ())
        self.assertEqual(FIELDS["dst.geo.country.code"]["type"], "country")
        self.assertEqual(FIELDS["dst.geo.country.code"]["category"], "geolocation")
        self.assertEqual(FIELDS["dst.geo.country.code"]["case_insensitive"], False)
        self.assertEqual(FIELDS["dst.geo.country.code"]["aliases"], ())
        self.assertEqual(FIELDS["dst.geo.country.code"]["enum"], ())
        self.assertEqual(FIELDS["dst.geo.country.name"]["type"], "country")
        self.assertEqual(FIELDS["dst.geo.country.name"]["category"], "geolocation")
        self.assertEqual(FIELDS["dst.geo.country.name"]["case_insensitive"], False)
        self.assertEqual(FIELDS["dst.geo.country.name"]["aliases"], ())
        self.assertEqual(FIELDS["dst.geo.country.name"]["enum"], ())
        self.assertEqual(FIELDS["dst.geo.city"]["type"], "keyword")
        self.assertEqual(FIELDS["dst.geo.city"]["category"], "geolocation")
        self.assertEqual(FIELDS["dst.geo.city"]["case_insensitive"], True)
        self.assertEqual(FIELDS["dst.geo.city"]["aliases"], ())
        self.assertEqual(FIELDS["dst.geo.city"]["enum"], ())
        self.assertEqual(FIELDS["dst.geo.continent.code"]["type"], "keyword")
        self.assertEqual(FIELDS["dst.geo.continent.code"]["category"], "geolocation")
        self.assertEqual(FIELDS["dst.geo.continent.code"]["case_insensitive"], False)
        self.assertEqual(FIELDS["dst.geo.continent.code"]["aliases"], ())
        self.assertEqual(FIELDS["dst.geo.continent.code"]["enum"], ())
        self.assertEqual(FIELDS["dst.geo.continent.name"]["type"], "keyword")
        self.assertEqual(FIELDS["dst.geo.continent.name"]["category"], "geolocation")
        self.assertEqual(FIELDS["dst.geo.continent.name"]["case_insensitive"], False)
        self.assertEqual(FIELDS["dst.geo.continent.name"]["aliases"], ())
        self.assertEqual(FIELDS["dst.geo.continent.name"]["enum"], ())
        self.assertEqual(FIELDS["dst.geo.latitude"]["type"], "float")
        self.assertEqual(FIELDS["dst.geo.latitude"]["category"], "geolocation")
        self.assertEqual(FIELDS["dst.geo.latitude"]["case_insensitive"], False)
        self.assertEqual(FIELDS["dst.geo.latitude"]["aliases"], ())
        self.assertEqual(FIELDS["dst.geo.latitude"]["enum"], ())
        self.assertEqual(FIELDS["dst.geo.longitude"]["type"], "float")
        self.assertEqual(FIELDS["dst.geo.longitude"]["category"], "geolocation")
        self.assertEqual(FIELDS["dst.geo.longitude"]["case_insensitive"], False)
        self.assertEqual(FIELDS["dst.geo.longitude"]["aliases"], ())
        self.assertEqual(FIELDS["dst.geo.longitude"]["enum"], ())
        self.assertEqual(FIELDS["http.path"]["type"], "text")
        self.assertEqual(FIELDS["http.path"]["category"], "http")
        self.assertEqual(FIELDS["http.path"]["case_insensitive"], True)
        self.assertEqual(FIELDS["http.path"]["aliases"], ("path",))
        self.assertEqual(FIELDS["http.path"]["enum"], ())
        self.assertEqual(FIELDS["http.user_agent"]["type"], "text")
        self.assertEqual(FIELDS["http.user_agent"]["category"], "http")
        self.assertEqual(FIELDS["http.user_agent"]["case_insensitive"], True)
        self.assertEqual(FIELDS["http.user_agent"]["aliases"], ("ua", "user_agent"))
        self.assertEqual(FIELDS["http.user_agent"]["enum"], ())
        self.assertEqual(FIELDS["ssh.auth.username"]["type"], "text")
        self.assertEqual(FIELDS["ssh.auth.username"]["category"], "ssh")
        self.assertEqual(FIELDS["ssh.auth.username"]["case_insensitive"], True)
        self.assertEqual(FIELDS["ssh.auth.username"]["aliases"], ("username",))
        self.assertEqual(FIELDS["ssh.auth.username"]["enum"], ())
        self.assertEqual(FIELDS["ssh.auth.password"]["type"], "text")
        self.assertEqual(FIELDS["ssh.auth.password"]["category"], "ssh")
        self.assertEqual(FIELDS["ssh.auth.password"]["case_insensitive"], True)
        self.assertEqual(FIELDS["ssh.auth.password"]["aliases"], ("password",))
        self.assertEqual(FIELDS["ssh.auth.password"]["enum"], ())
        self.assertEqual(FIELDS["ssh.auth.attempt_count"]["type"], "int")
        self.assertEqual(FIELDS["ssh.auth.attempt_count"]["category"], "ssh")
        self.assertEqual(FIELDS["ssh.auth.attempt_count"]["case_insensitive"], False)
        self.assertEqual(FIELDS["ssh.auth.attempt_count"]["aliases"], ())
        self.assertEqual(FIELDS["ssh.auth.attempt_count"]["enum"], ())
        self.assertEqual(FIELDS["ssh.auth.first_seen"]["type"], "date")
        self.assertEqual(FIELDS["ssh.auth.first_seen"]["category"], "ssh")
        self.assertEqual(FIELDS["ssh.auth.first_seen"]["case_insensitive"], False)
        self.assertEqual(FIELDS["ssh.auth.first_seen"]["aliases"], ())
        self.assertEqual(FIELDS["ssh.auth.first_seen"]["enum"], ())
        self.assertEqual(FIELDS["ssh.auth.last_seen"]["type"], "date")
        self.assertEqual(FIELDS["ssh.auth.last_seen"]["category"], "ssh")
        self.assertEqual(FIELDS["ssh.auth.last_seen"]["case_insensitive"], False)
        self.assertEqual(FIELDS["ssh.auth.last_seen"]["aliases"], ())
        self.assertEqual(FIELDS["ssh.auth.last_seen"]["enum"], ())
        self.assertEqual(FIELDS["fingerprints.muonfp"]["type"], "fingerprint")
        self.assertEqual(FIELDS["fingerprints.muonfp"]["category"], "fingerprints")
        self.assertEqual(FIELDS["fingerprints.muonfp"]["case_insensitive"], False)
        self.assertEqual(FIELDS["fingerprints.muonfp"]["aliases"], ("muonfp",))
        self.assertEqual(FIELDS["fingerprints.muonfp"]["enum"], ())
        self.assertEqual(FIELDS["fingerprints.ja4"]["type"], "fingerprint")
        self.assertEqual(FIELDS["fingerprints.ja4"]["category"], "fingerprints")
        self.assertEqual(FIELDS["fingerprints.ja4"]["case_insensitive"], False)
        self.assertEqual(FIELDS["fingerprints.ja4"]["aliases"], ("ja4",))
        self.assertEqual(FIELDS["fingerprints.ja4"]["enum"], ())
        self.assertEqual(FIELDS["fingerprints.ja4t"]["type"], "fingerprint")
        self.assertEqual(FIELDS["fingerprints.ja4t"]["category"], "fingerprints")
        self.assertEqual(FIELDS["fingerprints.ja4t"]["case_insensitive"], False)
        self.assertEqual(FIELDS["fingerprints.ja4t"]["aliases"], ("ja4t",))
        self.assertEqual(FIELDS["fingerprints.ja4t"]["enum"], ())
        self.assertEqual(FIELDS["fingerprints.ja4h"]["type"], "fingerprint")
        self.assertEqual(FIELDS["fingerprints.ja4h"]["category"], "fingerprints")
        self.assertEqual(FIELDS["fingerprints.ja4h"]["case_insensitive"], False)
        self.assertEqual(FIELDS["fingerprints.ja4h"]["aliases"], ("ja4h",))
        self.assertEqual(FIELDS["fingerprints.ja4h"]["enum"], ())
        self.assertEqual(FIELDS["fingerprints.ja4ssh"]["type"], "fingerprint")
        self.assertEqual(FIELDS["fingerprints.ja4ssh"]["category"], "fingerprints")
        self.assertEqual(FIELDS["fingerprints.ja4ssh"]["case_insensitive"], False)
        self.assertEqual(FIELDS["fingerprints.ja4ssh"]["aliases"], ("ja4ssh",))
        self.assertEqual(FIELDS["fingerprints.ja4ssh"]["enum"], ())
        self.assertEqual(FIELDS["fingerprints.ja3"]["type"], "fingerprint")
        self.assertEqual(FIELDS["fingerprints.ja3"]["category"], "fingerprints")
        self.assertEqual(FIELDS["fingerprints.ja3"]["case_insensitive"], False)
        self.assertEqual(FIELDS["fingerprints.ja3"]["aliases"], ("ja3",))
        self.assertEqual(FIELDS["fingerprints.ja3"]["enum"], ())
        self.assertEqual(FIELDS["tag"]["type"], "text")
        self.assertEqual(FIELDS["tag"]["category"], "intelligence")
        self.assertEqual(FIELDS["tag"]["case_insensitive"], True)
        self.assertEqual(FIELDS["tag"]["aliases"], ())
        self.assertEqual(FIELDS["tag"]["enum"], ())
        self.assertEqual(FIELDS["tag_id"]["type"], "text")
        self.assertEqual(FIELDS["tag_id"]["category"], "intelligence")
        self.assertEqual(FIELDS["tag_id"]["case_insensitive"], False)
        self.assertEqual(FIELDS["tag_id"]["aliases"], ())
        self.assertEqual(FIELDS["tag_id"]["enum"], ())
        self.assertEqual(FIELDS["actor"]["type"], "text")
        self.assertEqual(FIELDS["actor"]["category"], "intelligence")
        self.assertEqual(FIELDS["actor"]["case_insensitive"], True)
        self.assertEqual(FIELDS["actor"]["aliases"], ())
        self.assertEqual(FIELDS["actor"]["enum"], ())
        self.assertEqual(FIELDS["cve"]["type"], "text")
        self.assertEqual(FIELDS["cve"]["category"], "intelligence")
        self.assertEqual(FIELDS["cve"]["case_insensitive"], True)
        self.assertEqual(FIELDS["cve"]["aliases"], ())
        self.assertEqual(FIELDS["cve"]["enum"], ())
        self.assertEqual(FIELDS["mitre_attack.tactics"]["type"], "mitre")
        self.assertEqual(FIELDS["mitre_attack.tactics"]["category"], "intelligence")
        self.assertEqual(FIELDS["mitre_attack.tactics"]["case_insensitive"], False)
        self.assertEqual(FIELDS["mitre_attack.tactics"]["aliases"], ("tactic",))
        self.assertEqual(FIELDS["mitre_attack.tactics"]["enum"], ())
        self.assertEqual(FIELDS["mitre_attack.techniques"]["type"], "mitre")
        self.assertEqual(FIELDS["mitre_attack.techniques"]["category"], "intelligence")
        self.assertEqual(FIELDS["mitre_attack.techniques"]["case_insensitive"], False)
        self.assertEqual(FIELDS["mitre_attack.techniques"]["aliases"], ("technique",))
        self.assertEqual(FIELDS["mitre_attack.techniques"]["enum"], ())
        self.assertEqual(FIELDS["mitre_attack.sub_techniques"]["type"], "mitre")
        self.assertEqual(FIELDS["mitre_attack.sub_techniques"]["category"], "intelligence")
        self.assertEqual(FIELDS["mitre_attack.sub_techniques"]["case_insensitive"], False)
        self.assertEqual(FIELDS["mitre_attack.sub_techniques"]["aliases"], ("sub_technique",))
        self.assertEqual(FIELDS["mitre_attack.sub_techniques"]["enum"], ())


if __name__ == "__main__":
    unittest.main()
